server:
  port: 8080

app:
  push:
    base-url: http://localhost:9090ë¦¬

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - application-kafka.yml

---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - application-kafka.yml
